projectName: pikachu
domain: http://localhost:33333
env: local

database:
  dialect: mysql
  host: 127.0.0.1
  port: 53306 
  dbname: pikachu
  username: root
  password: mysqlvotmdnjem

readOnlyDatabase:
  dialect: mysql
  host: 127.0.0.1
  port: 53306 
  dbname: pikachu
  username: root
  password: mysqlvotmdnjem


redis:
  host: 127.0.0.1
  port: 56379